//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctthamquan
    {
        public int id { get; set; }
        public int idtour { get; set; }
        public int iddiadiem { get; set; }
    
        public virtual diadiem diadiem { get; set; }
        public virtual tour tour { get; set; }
    }
}
