//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class diadiem
    {
        public diadiem()
        {
            this.ctthamquans = new HashSet<ctthamquan>();
        }
    
        public int id { get; set; }
        public string tendiadiem { get; set; }
        public int idtinh { get; set; }
    
        public virtual ICollection<ctthamquan> ctthamquans { get; set; }
        public virtual tinh tinh { get; set; }
    }
}
