//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public khachhang()
        {
            this.doankhachhangs = new HashSet<doankhachhang>();
        }
    
        public int id { get; set; }
        public string tenkhachhang { get; set; }
        public string sodienthoai { get; set; }
        public string cmt { get; set; }
        public string diachi { get; set; }
        public int sex { get; set; }
    
        public virtual ICollection<doankhachhang> doankhachhangs { get; set; }
    }
}
