//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachsan
    {
        public khachsan()
        {
            this.doankhachsans = new HashSet<doankhachsan>();
        }
    
        public int id { get; set; }
        public string tenkhachsan { get; set; }
        public int idtinh { get; set; }
    
        public virtual ICollection<doankhachsan> doankhachsans { get; set; }
        public virtual tinh tinh { get; set; }
    }
}
