//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichsugiatour
    {
        public int id { get; set; }
        public int idtour { get; set; }
        public double giatour { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
    
        public virtual tour tour { get; set; }
    }
}
