//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhiemvu
    {
        public nhiemvu()
        {
            this.doannhanviens = new HashSet<doannhanvien>();
        }
    
        public int id { get; set; }
        public string tennhiemvu { get; set; }
    
        public virtual ICollection<doannhanvien> doannhanviens { get; set; }
    }
}
