//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class phuongtien
    {
        public phuongtien()
        {
            this.doanphuongtiens = new HashSet<doanphuongtien>();
        }
    
        public int id { get; set; }
        public string tenphuongtien { get; set; }
    
        public virtual ICollection<doanphuongtien> doanphuongtiens { get; set; }
    }
}
