//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour
    {
        public tour()
        {
            this.ctthamquans = new HashSet<ctthamquan>();
            this.doandulichs = new HashSet<doandulich>();
            this.lichsugiatours = new HashSet<lichsugiatour>();
        }
    
        public int id { get; set; }
        public string tentour { get; set; }
        public int diemden { get; set; }
        public int diemdi { get; set; }
        public string dacdiem { get; set; }
        public double giatour { get; set; }
        public int idtour { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaycapnhat { get; set; }
    
        public virtual ICollection<ctthamquan> ctthamquans { get; set; }
        public virtual ICollection<doandulich> doandulichs { get; set; }
        public virtual ICollection<lichsugiatour> lichsugiatours { get; set; }
        public virtual loaitour loaitour { get; set; }
        public virtual tinh tinh { get; set; }
        public virtual tinh tinh1 { get; set; }
    }
}
