//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tourdulichEntities : DbContext
    {
        public tourdulichEntities()
            : base("name=tourdulichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<chiphibuaan> chiphibuaans { get; set; }
        public DbSet<ctthamquan> ctthamquans { get; set; }
        public DbSet<diadiem> diadiems { get; set; }
        public DbSet<doanbuaan> doanbuaans { get; set; }
        public DbSet<doandulich> doandulichs { get; set; }
        public DbSet<doankhachhang> doankhachhangs { get; set; }
        public DbSet<doankhachsan> doankhachsans { get; set; }
        public DbSet<doannhanvien> doannhanviens { get; set; }
        public DbSet<doanphikhac> doanphikhacs { get; set; }
        public DbSet<doanphuongtien> doanphuongtiens { get; set; }
        public DbSet<khachhang> khachhangs { get; set; }
        public DbSet<khachsan> khachsans { get; set; }
        public DbSet<lichsugiatour> lichsugiatours { get; set; }
        public DbSet<loaitour> loaitours { get; set; }
        public DbSet<nhanvien> nhanviens { get; set; }
        public DbSet<nhiemvu> nhiemvus { get; set; }
        public DbSet<phuongtien> phuongtiens { get; set; }
        public DbSet<tinh> tinhs { get; set; }
        public DbSet<tour> tours { get; set; }
    }
}
